language: node_js
script:
- ./configure
- make .cache/site.tar
- make deploy
cache: true
env:
- secure: fRv9V8Dy5N1DWV/ydNRoHfwMdAnBQtKq+Rn6t7mliQ56VR6RsaIOhfbs5maRp/sMJe50tIaF3YFojDM+yjBRNk9QTEgl23iQ5q37YyOLl8jlUaL/sARU6n8NWm9stFuFcD2pMKWfaNIDKWPswyZNlfcSnHOzrQftwD8uEOPO4z9jrsptjNCv44cP9GI0TINAa4ZFY/IrFA6HumhwUFIiDe5C9K4LkaJ3mlUGu/OyLsOzhIUtvW48S6cO7hKplIIgR5Wv0clHI91NtNvxayO24JZ1IEwj88LuAyI2UP2MRKXqJIcudSPGAafcm3u/VlyO5RNOp7mfKZexMvrsGQ8Vsg==
