#!/usr/bin/env sh
# required argument: name of nix derivation
DIST=$(nix-build all-packages.nix -K -A $1)
COMMAND="(cd $DIST && python3 -m http.server)"

[ -z $DIST ] || nix-shell all-packages.nix -A pkgs.python3 --run "$COMMAND"

