.PHONY: clean deploy

clean:
    rm -rf build/*
    rm -rf tmp/*

deploy:
    (cd tmp/site; rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress . root@104.131.5.252:/root/teleport-json.org)


# Reinstall stuff if package.json is modified

node_modules: package.json
    npm install


#---------------------------------------------
# downloads
#---------------------------------------------

build/bootstrap-lumen.css:
    (cd build && wget http://bootswatch.com/lumen/bootstrap.css && mv bootstrap.css bootstrap-lumen.css)

build/bootstrap-3.3.0-dist.zip:
    (cd build && wget https://github.com/twbs/bootstrap/releases/download/v3.3.0/bootstrap-3.3.0-dist.zip)

build/bootstrap.tar: build/bootstrap-lumen.css build/bootstrap-3.3.0-dist.zip
    rm -rf tmp/bootstrap
    unzip build/bootstrap-3.3.0-dist.zip -d tmp
    mv tmp/dist tmp/bootstrap
    namespace-css build/bootstrap-lumen.css -s .bs -o tmp/bootstrap/css/bootstrap.css
    sed -i 's/\\.bs\\ body/\\.bs/g' tmp/bootstrap/css/bootstrap.css
    cp tmp/bootstrap/css/bootstrap.css tmp/bootstrap/css/bootstrap.min.css
    tar cf build/bootstrap.tar -C tmp/bootstrap .

build/flask-sphinx-themes.tar:
    wget https://github.com/cosmic-api/flask-sphinx-themes/archive/master.zip -O tmp/flask-sphinx-themes.zip
    rm -rf tmp/flask-sphinx-themes-master
    (cd tmp; unzip flask-sphinx-themes.zip)
    tar cf build/flask-sphinx-themes.tar -C tmp/flask-sphinx-themes-master .




#---------------------------------------------
# checkouts from git
#---------------------------------------------

{{#checkouts}}
{{{ out }}}: .git/refs/{{{ ref }}}
    git --git-dir .git archive $(shell cat .git/refs/{{{ ref }}}) > {{{ out }}}

{{/checkouts}}



#---------------------------------------------
# copying
#---------------------------------------------

{{#copy}}
{{{ to }}}: {{{ from }}}
    rm -rf {{{ to }}}
    cp -R {{{ from }}} {{{ to }}}

{{/copy}}




#---------------------------------------------
# building sphixes
#---------------------------------------------

{{#sphinxes}}
{{{ out }}}: {{{ source }}} build/flask-sphinx-themes.tar
    rm -rf {{{ tmp }}}
    mkdir {{{ tmp }}}
    tar xf {{{ source }}} -C {{{ tmp }}}
    mkdir {{{ tmp }}}/python/flask-sphinx-themes
    tar xf build/flask-sphinx-themes.tar -C {{{ tmp }}}/python/flask-sphinx-themes
    echo '\nhtml_theme_path = ["../../flask-sphinx-themes"]\n' >> {{{ tmp }}}/python/docs/source/conf.py
    echo '\nimport os, sys; sys.path.append(os.path.join(os.path.dirname(__file__), "../.."))\n' >> {{{ tmp }}}/python/docs/source/conf.py
    (cd {{{ tmp }}}/python; sphinx-build -b html -D html_theme=flask docs/source out)
    tar cf {{{ out }}} -C {{{ tmp }}}/python/out .

{{/sphinxes}}




#---------------------------------------------
# xml2rfc spec
#---------------------------------------------

{{#xml2rfc}}

{{{ out }}}: {{{ source }}} _site/spec.coffee _site/templates/spec.mustache
    rm -rf {{{ tmp }}}
    mkdir {{{ tmp }}}
    tar xf {{{ source }}} -C {{{ tmp }}}
    (cd {{{ tmp }}}/_spec; xml2rfc teleport.xml --text)
    mkdir {{{ tmp }}}/out
    {{{ coffeeExec }}} _site/spec.coffee < {{{ tmp }}}/_spec/teleport.txt > {{{ tmp }}}/out/index.html
    tar cf {{{ out }}} -C {{{ tmp }}}/out .

{{/xml2rfc}}




#---------------------------------------------
# injecting
#---------------------------------------------

{{#injections}}
{{{ out }}}: {{{ source }}} {{{ injectorDeps }}}
    rm -rf {{{ tmp }}}
    mkdir -p {{{ tmp }}}
    tar xf {{{ source }}} -C {{{ tmp }}}
    {{{ coffeeExec }}} _site/inject.coffee --dir {{{ tmp }}} {{{ injectorOpts }}}
    tar cf {{{ out }}} -C {{{ tmp }}} .

{{/injections}}



#---------------------------------------------
# site - putting everything together
#---------------------------------------------

build/site.tar: _site/static _site/index.coffee build/bootstrap.tar build/spec-new.tar {{{ injector }}} {{{ distDeps }}}
    rm -rf tmp/site
    mkdir -p tmp/site

    touch tmp/site/.nojekyll
    cp -R _site/static tmp/site
    rm -rf tmp/site/static/bootstrap
    mkdir -p tmp/site/static/bootstrap
    tar xf build/bootstrap.tar -C tmp/site/static/bootstrap

    {{{ coffeeExec }}} _site/index.coffee > tmp/site/index.html
    {{{ coffeeExec }}} _site/inject.coffee --file tmp/site/index.html --section home --nobs

    {{#dist}}
        mkdir -p tmp/site/{{{ dir }}}
        tar xf {{{ source }}} -C tmp/site/{{{ dir }}}

    {{/dist}}

    tar cf build/site.tar -C tmp/site .
